# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-02 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year', models.IntegerField(default=2016)),
                ('month', models.IntegerField(default=12)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-year',),
            },
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('publish', models.DateField(default=django.utils.timezone.now)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[['Domowe', 'Domowe'], ['Jedzenie', 'Jedzenie'], ['Kosmetyki i Chemia', 'Kosmetyki i Chemia'], ['Rozrywka', 'Rozrywka'], ['Okazyjne', 'Okazyjne'], ['Inne', 'Inne']], max_length=20)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost', to='core_sm.Budget')),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
    ]
