# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-11 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_sm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='slug',
        ),
    ]
