# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_sm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cost',
            name='date',
        ),
        migrations.AlterField(
            model_name='cost',
            name='category',
            field=models.CharField(choices=[('Domowe', 'Domowe'), ('Jedzenie', 'Jedzenie'), ('Kosmetyki i Chemia', 'Kosmetyki i Chemia'), ('Rozrywka', 'Rozrywka'), ('Okazyjne', 'Okazyjne'), ('Inne', 'Inne')], max_length=20),
        ),
        migrations.DeleteModel(
            name='DateMonthYear',
        ),
    ]
