# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-22 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core_sm', '0002_auto_20161116_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cost',
            name='slug',
        ),
        migrations.AlterField(
            model_name='cost',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cost',
            name='publish',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cost',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
