# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-18 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_sm', '0002_remove_budget_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('-title',),
            },
        ),
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ('-created',)},
        ),
        migrations.RemoveField(
            model_name='budget',
            name='month',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='year',
        ),
        migrations.AlterField(
            model_name='cost',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost', to='core_sm.Category'),
        ),
    ]
