# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-01 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core_sm', '0003_auto_20161218_1507'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ('-publish',)},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-publish',)},
        ),
        migrations.RemoveField(
            model_name='budget',
            name='created',
        ),
        migrations.AddField(
            model_name='budget',
            name='publish',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budget',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='category',
            name='publish',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
