# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-30 05:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_sm', '0003_auto_20161122_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(default=datetime.datetime(2016, 11, 30, 5, 59, 1, 841255), unique=True)),
                ('january', models.DecimalField(decimal_places=2, max_digits=10, unique_for_month=1, unique_for_year=models.DateField(default=datetime.datetime(2016, 11, 30, 5, 59, 1, 841255), unique=True))),
                ('february', models.DecimalField(decimal_places=2, max_digits=10, unique_for_month=2, unique_for_year=models.DateField(default=datetime.datetime(2016, 11, 30, 5, 59, 1, 841255), unique=True))),
                ('march', models.DecimalField(decimal_places=2, max_digits=10, unique_for_month=3, unique_for_year=models.DateField(default=datetime.datetime(2016, 11, 30, 5, 59, 1, 841255), unique=True))),
                ('april', models.DecimalField(decimal_places=2, max_digits=10, unique_for_month=4, unique_for_year=models.DateField(default=datetime.datetime(2016, 11, 30, 5, 59, 1, 841255), unique=True))),
                ('may', models.DecimalField(decimal_places=2, max_digits=10, unique_for_month=5, unique_for_year=models.DateField(default=datetime.datetime(2016, 11, 30, 5, 59, 1, 841255), unique=True))),
                ('june', models.DecimalField(decimal_places=2, max_digits=10, unique_for_month=6, unique_for_year=models.DateField(default=datetime.datetime(2016, 11, 30, 5, 59, 1, 841255), unique=True))),
                ('july', models.DecimalField(decimal_places=2, max_digits=10, unique_for_month=7, unique_for_year=models.DateField(default=datetime.datetime(2016, 11, 30, 5, 59, 1, 841255), unique=True))),
                ('august', models.DecimalField(decimal_places=2, max_digits=10, unique_for_month=8, unique_for_year=models.DateField(default=datetime.datetime(2016, 11, 30, 5, 59, 1, 841255), unique=True))),
                ('september', models.DecimalField(decimal_places=2, max_digits=10, unique_for_month=9, unique_for_year=models.DateField(default=datetime.datetime(2016, 11, 30, 5, 59, 1, 841255), unique=True))),
                ('october', models.DecimalField(decimal_places=2, max_digits=10, unique_for_month=10, unique_for_year=models.DateField(default=datetime.datetime(2016, 11, 30, 5, 59, 1, 841255), unique=True))),
                ('november', models.DecimalField(decimal_places=2, max_digits=10, unique_for_month=11, unique_for_year=models.DateField(default=datetime.datetime(2016, 11, 30, 5, 59, 1, 841255), unique=True))),
                ('december', models.DecimalField(decimal_places=2, max_digits=10, unique_for_month=12, unique_for_year=models.DateField(default=datetime.datetime(2016, 11, 30, 5, 59, 1, 841255), unique=True))),
            ],
        ),
        migrations.AlterField(
            model_name='cost',
            name='category',
            field=models.CharField(choices=[['Domowe', 'Domowe'], ['Jedzenie', 'Jedzenie'], ['Kosmetyki i Chemia', 'Kosmetyki i Chemia'], ['Rozrywka', 'Rozrywka'], ['Okazyjne', 'Okazyjne'], ['Inne', 'Inne']], max_length=20),
        ),
    ]
