# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-30 15:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_sm', '0004_auto_20161130_0559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='date',
        ),
        migrations.AddField(
            model_name='budget',
            name='end_date',
            field=models.DateField(default=datetime.date(2016, 12, 31), unique=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='start_date',
            field=models.DateField(default=datetime.date(2016, 1, 1), unique=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='april',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='budget',
            name='august',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='budget',
            name='december',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='budget',
            name='february',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='budget',
            name='january',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='budget',
            name='july',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='budget',
            name='june',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='budget',
            name='march',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='budget',
            name='may',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='budget',
            name='november',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='budget',
            name='october',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='budget',
            name='september',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
